# Site settings
title: Binary Developers
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://deveopers.binary.com"
twitter_username: binarydotcom
github_username:  binary-com

# Build settings
markdown: kramdown

collections:
  pages:
    output: true
    permalink: /:path/
